import type { Task } from '../types';

export type TaskPresetId = 'chores' | 'work' | 'social' | 'adhoc' | 'meetup';

export interface TaskPreset {
  id: TaskPresetId;
  label: string;
  hint: string;
  placeholder: string;
  defaults: Partial<Task>;
}

export const TASK_PRESETS: Record<TaskPresetId, TaskPreset> = {
  chores: {
    id: 'chores',
    label: 'Chores',
    hint: 'Low-friction home upkeep',
    placeholder: 'Take out recycling',
    defaults: {
      tag: 'general',
      effort: 'low',
      duration: 20,
      deadlineType: 'soft',
      timeSensitivity: 0.35,
      recurrence: 'weekly',
      focusType: 'shallow',
      cognitiveLoad: 0.22,
      emotionalResistance: 0.2,
      activationEnergy: 0.25,
      recoveryCost: 0.12,
      importance: 0.35,
      urgency: 0.3,
      consequenceOfDelay: 0.2,
      momentumValue: 0.45,
      compoundBenefit: 0.35,
      identityAlignment: 0.55,
      historicalCompletionRate: 0.65,
      preferredExecutionWindow: 'afternoon',
      taskDecompositionPotential: 0.25,
      energyToRewardRatio: 0.75,
      locationDependency: 'home',
    },
  },
  work: {
    id: 'work',
    label: 'Work',
    hint: 'Focused professional work',
    placeholder: 'Draft project update',
    defaults: {
      tag: 'work',
      effort: 'medium',
      duration: 45,
      deadlineType: 'soft',
      timeSensitivity: 0.7,
      focusType: 'deep',
      cognitiveLoad: 0.65,
      emotionalResistance: 0.4,
      activationEnergy: 0.6,
      recoveryCost: 0.35,
      importance: 0.8,
      urgency: 0.55,
      consequenceOfDelay: 0.65,
      momentumValue: 0.5,
      compoundBenefit: 0.6,
      identityAlignment: 0.7,
      historicalCompletionRate: 0.55,
      preferredExecutionWindow: 'morning',
      taskDecompositionPotential: 0.55,
      energyToRewardRatio: 0.45,
    },
  },
  social: {
    id: 'social',
    label: 'Social',
    hint: 'Connection and outreach',
    placeholder: 'Text Alex to plan dinner',
    defaults: {
      tag: 'social',
      effort: 'low',
      duration: 30,
      deadlineType: 'soft',
      timeSensitivity: 0.45,
      focusType: 'shallow',
      cognitiveLoad: 0.3,
      emotionalResistance: 0.45,
      activationEnergy: 0.35,
      recoveryCost: 0.2,
      importance: 0.55,
      urgency: 0.4,
      consequenceOfDelay: 0.25,
      momentumValue: 0.6,
      compoundBenefit: 0.4,
      identityAlignment: 0.75,
      historicalCompletionRate: 0.5,
      preferredExecutionWindow: 'evening',
      taskDecompositionPotential: 0.2,
      energyToRewardRatio: 0.8,
    },
  },
  adhoc: {
    id: 'adhoc',
    label: 'Ad hoc',
    hint: 'Quick one-off errand',
    placeholder: 'Pick up prescription',
    defaults: {
      tag: 'general',
      effort: 'low',
      duration: 15,
      deadlineType: 'none',
      timeSensitivity: 0.5,
      focusType: 'shallow',
      cognitiveLoad: 0.28,
      emotionalResistance: 0.25,
      activationEnergy: 0.3,
      recoveryCost: 0.15,
      importance: 0.4,
      urgency: 0.55,
      consequenceOfDelay: 0.35,
      momentumValue: 0.25,
      compoundBenefit: 0.2,
      identityAlignment: 0.35,
      historicalCompletionRate: 0.6,
      taskDecompositionPotential: 0.1,
      energyToRewardRatio: 0.7,
    },
  },
  meetup: {
    id: 'meetup',
    label: 'Meetup',
    hint: 'Time-bound social event',
    placeholder: 'Coffee with Sam at 3pm',
    defaults: {
      tag: 'social',
      effort: 'low',
      duration: 60,
      deadlineType: 'hard',
      timeSensitivity: 0.9,
      focusType: 'shallow',
      cognitiveLoad: 0.25,
      emotionalResistance: 0.35,
      activationEnergy: 0.3,
      recoveryCost: 0.25,
      importance: 0.5,
      urgency: 0.75,
      consequenceOfDelay: 0.55,
      momentumValue: 0.4,
      compoundBenefit: 0.3,
      identityAlignment: 0.65,
      historicalCompletionRate: 0.7,
      preferredExecutionWindow: 'afternoon',
      taskDecompositionPotential: 0.15,
      energyToRewardRatio: 0.65,
      locationDependency: 'out',
    },
  },
};

export const TASK_PRESET_IDS = Object.keys(TASK_PRESETS) as TaskPresetId[];
